export async function generateWithGemini(
  prompt: string,
  apiKeyName: 'GEMINI_API_KEY' | 'GEMINI_RESEARCH_KEY' = 'GEMINI_API_KEY',
) {
  const apiKey =
    apiKeyName === 'GEMINI_RESEARCH_KEY'
      ? process.env.GEMINI_RESEARCH_KEY
      : process.env.GEMINI_API_KEY;

  if (!apiKey) {
    console.log(`No ${apiKeyName} found, returning mock response`);
    const mockResponses: Record<string, string> = {
      GEMINI_API_KEY:
        'Mock resume content for testing purposes. This is a sample resume generated for testing the UI.',
      GEMINI_RESEARCH_KEY:
        'Mock company research content for testing purposes. This is sample research generated for testing the UI.',
    };
    return mockResponses[apiKeyName] || 'Mock content generated for testing.';
  }

  try {
    console.log(
      `Calling Gemini API (${apiKeyName}) with prompt length:`,
      prompt.length,
    );
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent?key=${apiKey}`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [{ text: prompt }],
            },
          ],
        }),
      },
    );

    if (!response.ok) {
      console.error('Gemini API error:', response.status, response.statusText);
      const errorText = await response.text();
      console.error('Error response:', errorText);
      return `Error: Gemini API returned ${response.status} - ${response.statusText}`;
    }

    const data = await response.json();
    console.log('Gemini API response received');
    const content = data.candidates?.[0]?.content?.parts?.[0]?.text ?? '';
    console.log('Generated content length:', content.length);
    return content || 'No content was generated by the AI.';
  } catch (error) {
    console.error('Error calling Gemini API:', error);
    return 'Error: Failed to call Gemini API. Please check your internet connection and API key.';
  }
}
